//------------------------------------------------------------------------------
// <auto-generated>
//     Ten kod został wygenerowany przez narzędzie.
//     Wersja wykonawcza:4.0.30319.42000
//
//     Zmiany w tym pliku mogą spowodować nieprawidłowe zachowanie i zostaną utracone, jeśli
//     kod zostanie ponownie wygenerowany.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Your_Kcal_Day.Properties {
    using System;
    
    
    /// <summary>
    ///   Klasa zasobu wymagająca zdefiniowania typu do wyszukiwania zlokalizowanych ciągów itd.
    /// </summary>
    // Ta klasa została automatycznie wygenerowana za pomocą klasy StronglyTypedResourceBuilder
    // przez narzędzie, takie jak ResGen lub Visual Studio.
    // Aby dodać lub usunąć składową, edytuj plik ResX, a następnie ponownie uruchom narzędzie ResGen
    // z opcją /str lub ponownie utwórz projekt VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        /// Zwraca buforowane wystąpienie ResourceManager używane przez tę klasę.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Your_Kcal_Day.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Przesłania właściwość CurrentUICulture bieżącego wątku dla wszystkich
        ///   przypadków przeszukiwania zasobów za pomocą tej klasy zasobów wymagającej zdefiniowania typu.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Nazwa,Kcal,Bialko,Weglowodany,Tluszcz
        ///Woda,0,0,0,0
        ///Pomidor,18,0.9,3.9,0.2
        ///&quot;Oliwa z oliwek&quot;,884,0,0,100
        ///&quot;Pieprz czarny&quot;,255,11,64.8,3.5
        ///Banan,89,1,22,0.3
        ///Czosnek,149,6.4,33.1,0.5
        ///&quot;Cebula (świeża)&quot;,40,1.1,7.6,0.1
        ///&quot;Jabłko (świeży owoc)&quot;,57,0.3,13.8,0.2
        ///&quot;Sól biała&quot;,0,0,0,0
        ///&quot;Marchew (surowa)&quot;,41,0.9,9.6,0.2
        ///Ogórek,15,0.7,3.6,0.1
        ///&quot;Sól morska&quot;,0,0,0,0
        ///&quot;Płatki owsiane&quot;,389,16.9,66.3,6.9
        ///&quot;Sok z cytryny&quot;,22,0.4,6.9,0.2
        ///&quot;Chleb żytni razowy&quot;,217,6.7,41.5,1.2
        ///Sałata,13,1.4,2.2,0.2
        ///&quot;Papryka czerwona&quot;,28,1.3,6.6,0.5
        ///Rzodk [obcięto pozostałą część ciągu]&quot;;.
        /// </summary>
        internal static string CSVFile {
            get {
                return ResourceManager.GetString("CSVFile", resourceCulture);
            }
        }
    }
}
